---
title: "ML for Remote Sensing"
description: "Presentation slides and resource collections from the ICLR 2023 Workshop."
toc: true
include-in-header: 
  text: |
    <script src="../assets/js/system-init.js"></script>
---

# ML for Remote Sensing: Resource Collection

## Workshop Presentations & Slides

| Topic | Resource | Instructor |
| :--- | :--- | :--- |
| **Data Overview** | [Presentation Slides](https://docs.google.com/presentation/d/e/2PACX-1vSsaX5ICC_wphrY7vvLmvv2eCrfHqTKXoMy4DIK-GIC0MRhyogyKtv_qrkAbj5ZX3MDvbK-fNXdNK-o/pub?start=false&loop=false&delayms=3000) | Hannah Kerner |
| **ML Methods** | [Presentation Slides](https://docs.google.com/presentation/d/e/2PACX-1vS59rUlWqYE59SjSSjhS2rlZZ_2XthvzTlbuBFM1hwJ4MAWidoQZfeVnJZ-hUzOcJIYgSrIn-h9jYRF/pub?start=false&loop=false&delayms=3000) | Gabi Tseng |
| **Data Considerations** | [Presentation Slides](https://docs.google.com/presentation/d/e/2PACX-1vQ4WCS4BntgpSsze-gTog9AIHbh4KQp5M9PwYBPb8UUElba1y5AMR3ge1b05p8lqTSdaeo8swGKZa1y/pub?start=false&loop=false&delayms=3000) | Ivan Zvonkov |
| **EO for Agriculture** | [Presentation Slides](https://docs.google.com/presentation/d/e/2PACX-1vSf38k5Ph2zzUm6NjV0Uh9X8p55o_P0UbLZoD59FON8zLfZcQtFwSgmApQj7agJw5lVOrk6WyJW517a/pub?start=false&loop=false&delayms=3000) | Catherine Nakalembe |
| **NASA Harvest Case Study** | [Presentation Slides](https://docs.google.com/presentation/d/e/2PACX-1vSJHrvWsxjcB6JHj2Cu8PMbSYO83AFJnBS-BAEYpm5bKJ2URXNpAi9A5E0mGT3myxmlDZOpBXBz8uMf/pub?start=false&loop=false&delayms=3000) | Ivan Zvonkov |
| **Predictions to Insights** | [Presentation Slides](https://docs.google.com/presentation/d/10ctlRkySINwcE7zKvWYPvVlwVklsT5hj97HDQRjYyoM/edit?usp=sharing) | Gedeon Muhawenayo |
| **Networking & Break** | [Slide Collection](https://docs.google.com/presentation/d/e/2PACX-1vR2F1lmmffd2qQ4hXkPwd0ldhiPUkb2gvob-x29F9SXXClITmDCc9GqY3e_s2KX7XsgqDkDjufRGg_c/pub?start=false&loop=false&delayms=3000) | |

<br>

## Research Papers & External Links

| Resource Type | Title / Link | Description |
| :--- | :--- | :--- |
| **Research Paper** | [Towards Explainable Land Cover Mapping](https://raw.githubusercontent.com/nasaharvest/ml-for-remote-sensing/main/iclr2023/papers/10/CameraReady/2023_CounterFactualSITS_ICLR_workshop_Camera-ready.pdf) | Counterfactual-based strategy for land cover. |
| **Research Paper** | [Agricultural Poverty Prediction](https://raw.githubusercontent.com/nasaharvest/ml-for-remote-sensing/main/iclr2023/papers/35/CameraReady/ICLRCameraReady.pdf) | Satellite-based disparities in prediction. |
| **Research Paper** | [Acoustic Classification Enhancement](https://raw.githubusercontent.com/nasaharvest/ml-for-remote-sensing/main/iclr2023/papers/43/CameraReady/Enhancing_Acoustic_Classification_ICLR_2023_Jeantet_Dufourq.pdf) | Using Meta-Data for acoustic ML. |
| **Official Site** | [Workshop Website](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2023/) | Official ICLR 2023 ML4RS page. |
| **Code Repository** | [NASA Harvest GitHub](https://github.com/nasaharvest) | Open-source geospatial tools. |
| **Course** | [NASA ARSET](https://appliedsciences.nasa.gov/what-we-do/capacity-building/arset) | Applied Remote Sensing Training. |
| **Book** | [EEFA Book](https://www.eefabook.org/) | Cloud-Based RS with Earth Engine. |

<br>

## ICLR 2024 Accepted Papers & Posters

| Resource Type | Title / Link | Authors |
| :--- | :--- | :--- |
| **Poster** | Learned Embedding Fields for Multi-Source, Multi-Temporal Earth Observation Imagery <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/2.pdf) | Brown , Christopher F; Kazmierski , Michal R; Rucklidge, William J; Pasquarella, Valerie J.; Shelhamer, Evan |
| **Poster** | [GIMI: A Geographical Generalizable Image-to-Image Search Engine with Location-explicit Contrastive Embedding](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/4.pdf) <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/4.pdf) | Li, Hao; Wang, Jiapan; Teuscher, Balthasar; Luo, Peng; Hong, Danfeng; Mai, Gengchen; Werner, Martin |
| **Poster** | [Uncertainty quantification for probabilistic machine learning in earth observation using conformal prediction](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/6.pdf) <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/6.pdf) | Singh, Geethen, Tamara B. Robinson, Glenn Moncrieff, Zander S. Venter, Kerry-Cawse Nicholson, Jasper Slingsby |
| **Paper** | [Super-resolution of Sentinel-1 Imagery Using an Enhanced Attention Network and Real Ground Truth Data](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/9.pdf) | Ayala, Christian; Amieva, Juan Francisco; Galar, Mikel |
| **Paper** | [Multi-stage semantic segmentation to map small and sparsely distributed habitats](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/10.pdf) | van der Plas, Thijs Lambik; Geikie, Simon; Alexander, David; Simms, Daniel |
| **Poster** | [Noise2Noise Denoising of CRISM Hyperspectral Data](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/11.pdf) <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/11.pdf) | Platt, Robert; John, Cedric; Arcucci, Rossella |
| **Paper** | [A Concise Tiling Strategy for Preserving Spatial Context in Earth Observation Imagery](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/13.pdf) | Abrahams, Ellianna; Snow, Tasha; Pérez, Fernando; Siegfried, Matthew |
| **Poster** | [Impact of Missing Views in Multi-view Model Predictions for Vegetation Applications](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/14.pdf) <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/14.pdf) | Mena, Francisco; Arenas, Diego; Nuske, Marlon; Dengel, Andreas |
| **Paper** | [Integrating physics deductive biases into learning for hyperspectral classification](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/17.pdf) | Thoreau, Romain* |
| **Poster** | [AI-powered School Mapping and Connectivity Status Prediction using Earth Observation](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/24.pdf) <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/24.pdf) | Doerksen, Kelsey; Tingzon, Isabelle; Kim, Dohyung |
| **Poster** | [Towards general deep-learning-based tree instance segmentation models](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/28.pdf) <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/28.pdf) | Henrich, Jonathan; van Delden, Jan |
| **Paper** | [Composite Augmentations for Semantic Segmentation in Aerial Images with Few Samples](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/29.pdf) | Chandramouli, Pranav; Stavness, Ian ; McLoughlin, Phillip; Neufeld, Branden |
| **Paper** | [On the Relevance of SAR and Optical Modalities in Deep Learning based Data Fusion](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/31.pdf) | Gawlikowski, Jakob; Gottschling, Nina Maria |
| **Paper** | [Red Teaming Models for Hyperspectral Image Analysis Using Explainable AI](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/32.pdf) | Zaigrajew, Vladimir; Baniecki, Hubert; Tulczyjew, Lukasz; Wijata, Agata Maria; Nalepa, Jakub; Longepe, Nicolas; Biecek, Przemyslaw |
| **Poster** | [Leveraging 3d Model Imagery To Estimate A New Window View Index](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/33.pdf) <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/33.pdf) | Law, Stephen; Stalder, Steven; Suel, Esra; Takizawa, Atsushi |
| **Poster** | [High-resolution Multi-spectral Image Guided DEM Super-resolution using Sinkhorn Regularized Adversarial Network](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/34.pdf) <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/34.pdf) | Paul, Subhajit; Gupta, Ashutosh |
| **Poster** | [Efficient Remote Sensing with Harmonized Transfer Learning and Modality Alignment](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/35.pdf) <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/35.pdf) | Huang, Tengjun* |
| **Poster** | [Exploring selective simple image matching methods for Unsupervised Domain adaptation of urban canopy cover and height prediction](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/37.pdf) <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/37.pdf) | Francis, John; Law, Stephen |
| **Paper** | [Impacts of Color and Texture Distortions on Earth Observation Data in Deep Learning](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/40.pdf) | Willbo, Martin; Pirinen, Aleksis; Martinsson, John; Listo Zec, Edvin; Mogren, Olof; Nilsson, Mikael |
| **Paper** | [Towards Climate Variable Prediction with Conditioned Spatio-Temporal Normalizing Flows](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/41.pdf) | Winkler, Christina Elisabeth; Rolnick, David |
| **Paper** | [Limitations of non-traditional data: evaluating satellite data and OpenStreetMap for predicting spatio-temporal variation in material wealth](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/43.pdf) | Schmidt-Ott, Nathanael; Kis-Katos, Krisztina |
| **Paper** | [Global Above-Ground Biomass Density Estimation from Sentinel-2 Imagery](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/45.pdf) | Bereczky, Max; Hei, Ka ; Rashkovetsky, Dima; Gottfriedsen, Julia* |
| **Poster** | [A Change Detection Reality Check](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/46.pdf) <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/46.pdf) | Corley, Isaac A; Robinson, Caleb; Ortiz, Anthony |
| **Poster** | [Global Mapping of Exposure and Physical Vulnerability Dynamics in Least Developed Countries using Remote Sensing and Machine Learning](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/48.pdf) <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/48.pdf) | Dimasaka, Joshua T; Emily So; Christian Geiß |
| **Poster** | [Bootstrapping Rare Object Detection in High-Resolution Satellite Imagery](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/49.pdf) <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/49.pdf) | Zaytar, Akram; Robinson, Caleb; Quentin Hacheme, Gilles; Tadesse, Girmaw Abebe; Dodhia, Rahul ; Lavista Ferres, Juan M |
| **Poster** | [ESO: Evolutionary Spectrogram Optimisation for Passive Acoustic Monitoring](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/51.pdf) <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/51.pdf) | Çakır, Ufuk; Jeantet, Lorène LJ; Lontsi Sob, Aaron Joel A J; Dufourq, Emmanuel |
| **Paper** | [Spatiotemporal Rockfall Detection Using Point-Based Neural Networks](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/53.pdf) | Zoumpekas, Thanasis; Puig, Anna; Salamó, Maria |
| **Poster** | [Leveraging Deep Learning for the Reconstruction of Plant Hyperspectral Data from RGB Images](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/55.pdf) <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/55.pdf) | Sarkis, Serge; Issa, Ibrahim; Abou Jaoude, Dany; Talhouk, Salma |
| **Poster** | [Learning Source Domain Representations for Electro-Optical to SAR Transfer](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/56.pdf) <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/56.pdf) | Zeng, Boya; Hussing, Marcel; Eaton, Eric |
| **Paper** | [Region-Level Labels In Ice Charts Can Produce Pixel-Level Segmentation For Sea Ice Types](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/59.pdf) | Patel, Muhammed; Chen, Xinwei; Xu, Linlin; Chen, Yuhao; Scott, K Andrea; Clausi, David A |
| **Poster** | [Spatially Far, Ecologically Close: Evaluating Extrapolation on Vegetation Forecasting Models](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/60.pdf) <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/60.pdf) | Robin, Claire; Weynants, Melanie; Benson, Vitus; Rußwurm, Marc; Carvalhais, Nuno; Reichstein, Markus |
| **Paper** | [Seeing Through the Clouds: Cloud Gap Imputation with Prithvi Foundation Model](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/61.pdf) | Godwin, Denys; Li, Hanxi; Cecil, Michael; Alemohammad, Hamed |
| **Poster** | [Encoding Agent Trajectories as Representations with Sequence Transformers](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/62.pdf) <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/62.pdf) | Tsiligkaridis, Athanasios; Li, Zhongheng; Hou, Elizabeth |
| **Paper** | [Synthetic data augmentation for earth observation object detection tasks](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/66.pdf) | Khammari, Syrine; Fernández-Laguilhoat Sánchez-Biezma , Enrique; Sukhanov , Sergey ; Tankoyeu, Ivan |
| **Poster** | [A Benchmark For Geographic Distribution Shift In Smallholder Agroforestry: Do Foundation Models Improve Ood Generalization?](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/69.pdf) <br> [[Poster]](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/posters/69.pdf) | Sachdeva, Siddharth; Biradar, Chandrasekhar; Lopez, Isabel; Lobell, David |
| **Paper** | [Physics Informed Modeling of Ecosystem Respiration via Dynamic Mode Decomposition with Control Input](https://nasaharvest.github.io/ml-for-remote-sensing/iclr2024/camera_ready/papers/72.pdf) | Shadaydeh, Maha; Denzler, Joachim; Migliavacca, Mirco |

