// questions.js
export const originalQuestions = [
    { q: "What is the primary purpose of the Google Earth Engine Data Catalog?", options: ["To store personal datasets", "To provide public datasets for analysis", "To visualize data in 3D", "To edit vector data"], answer: "To provide public datasets for analysis", explanation: "The GEE Data Catalog provides a vast collection of satellite imagery and geospatial datasets for analysis." },
    { q: "Which section of the GEE Code Editor is used to view and manage datasets?", options: ["Inspector", "Map", "Console", "Scripts"], answer: "Scripts", explanation: "The Scripts section allows users to manage, edit, and save their code files and projects." },
    { q: "What is the function of the 'Inspector' tab in the GEE Code Editor?", options: ["To write and run code", "To inspect pixel values and properties", "To apply visualizations", "To view error messages"], answer: "To inspect pixel values and properties", explanation: "The Inspector tool allows users to click on the map and view pixel values, properties, and feature details." },
    { q: "Which function is used to load datasets from the Data Catalog in Google Earth Engine?", options: ["ee.ImageCollection", "ee.Dataset", "ee.Load", "ee.Feature"], answer: "ee.ImageCollection", explanation: "The ee.ImageCollection function is often used to load satellite imagery datasets from the catalog." },
    { q: "What is the purpose of the 'Map' object in GEE?", options: ["To store feature data", "To run reducers", "To display images and vectors on the map", "To filter datasets"], answer: "To display images and vectors on the map", explanation: "The Map object is used for visualizing geospatial data using layers." },
    { q: "Which file format is commonly used to export raster data from GEE?", options: ["CSV", "GeoJSON", "GeoTIFF", "Shapefile"], answer: "GeoTIFF", explanation: "GeoTIFF is a popular format for exporting raster data as it preserves geospatial information." },
    { q: "What does 'ee.Image' represent in Google Earth Engine?", options: ["A single satellite image or raster layer", "A vector feature", "A table of data", "A JavaScript object"], answer: "A single satellite image or raster layer", explanation: "An ee.Image represents a raster dataset, often derived from satellite sensors." },
    { q: "How can you filter an ImageCollection in GEE?", options: ["Using Map.addLayer", "Using ee.Filter", "Using ee.Dictionary", "Using Export.image"], answer: "Using ee.Filter", explanation: "The ee.Filter function is commonly used to filter an ImageCollection by date, bounds, or properties." },
    { q: "Which of the following is NOT a valid data type in GEE?", options: ["ee.Geometry", "ee.Number", "ee.Vector", "ee.String"], answer: "ee.Vector", explanation: "GEE does not have an ee.Vector type; vector data is represented using ee.Geometry or ee.Feature." },
    { q: "What is the purpose of the 'Console' section in the GEE Code Editor?", options: ["To inspect code execution logs and outputs", "To manage datasets", "To view map layers", "To write feature data"], answer: "To inspect code execution logs and outputs", explanation: "The Console displays messages, results from print statements, and errors from code execution." }
  ];